name: SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
